import './style.scss'
import './commonStyles.scss'
import './font.scss'
import './layout/header/header.scss'
import './layout/main/main.scss'
import './layout/courses/courses.scss'
import './layout/footer/footer.scss'
